name: app_store
description: A new Flutter project for an app store.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Updated to a compatible SDK version

dependencies:
  flutter:
    sdk: flutter

  # Dependencies for state management, HTTP requests, and UI components.
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  provider: ^6.0.3

  # Additional Dependencies (if needed for your Flutter app's styling)
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint rules for Flutter analysis (updated version to avoid conflict)
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Adding fonts and assets to be used in the app
  assets:
    - assets/ # Directory for images, icons, etc.
    - assets/icons/
    - assets/banner.jpg
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

# Removed the dependency override for 'analyzer' as it caused version conflicts.
